project:
  type: book

book:
  title: "Developing a Data Pipeline"
  subtitle: "MACEPA Data Fellowship - Training Materials"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 

editor: visual

