project:
  type: book

book:
  title: Developing a Data Pipeline
  subtitle: MACEPA Data Fellowship - Training Materials
  date: "12/2/2024"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 
  pdf:
    documentclass: scrreprt
editor: visual

